### ISSUE TITLE
unable to compile with g++-3.3 (Trac #148)

### ISSUE THREAD

**Issue by danmar** [danmar/testissues#148]
Migrated from https://trac.cppcheck.net/ticket/148
```json
{
    "status": "closed", 
    "changetime": "2009-03-08T18:53:22", 
    "description": "i tried to compile the project with g++ version 3.3 on an ubuntu linux system. I get the following error message:\n\ng++-3.3 -Wall -pedantic -g  -c -o src/checkbufferoverrun.o src/checkbufferoverrun.cpp\ng++-3.3 -Wall -pedantic -g  -c -o src/checkclass.o src/checkclass.cpp\ng++-3.3 -Wall -pedantic -g  -c -o src/checkdangerousfunctions.o src/checkdangerousfunctions.cpp\ng++-3.3 -Wall -pedantic -g  -c -o src/checkfunctionusage.o src/checkfunctionusage.cpp\ng++-3.3 -Wall -pedantic -g  -c -o src/checkheaders.o src/checkheaders.cpp\ng++-3.3 -Wall -pedantic -g  -c -o src/checkmemoryleak.o src/checkmemoryleak.cpp\ng++-3.3 -Wall -pedantic -g  -c -o src/checkother.o src/checkother.cpp\ng++-3.3 -Wall -pedantic -g  -c -o src/checksecurity.o src/checksecurity.cpp\ng++-3.3 -Wall -pedantic -g  -c -o src/checkstl.o src/checkstl.cpp\ng++-3.3 -Wall -pedantic -g  -c -o src/cppcheck.o src/cppcheck.cpp\ng++-3.3 -Wall -pedantic -g  -c -o src/cppcheckexecutor.o src/cppcheckexecutor.cpp\ng++-3.3 -Wall -pedantic -g  -c -o src/errorlogger.o src/errorlogger.cpp\n/usr/include/c++/3.3/bits/stl_iterator_base_types.h: In instantiation of `std::iterator_traits<int>':\n/usr/include/c++/3.3/bits/basic_string.h:624:   instantiated from `std::basic_string<_CharT, _Traits, _Alloc>& std::basic_string<_CharT, _Traits, _Alloc>::replace(__gnu_cxx::__normal_iterator<typename _Alloc::pointer, std::basic_string<_CharT, _Traits, _Alloc> >, __gnu_cxx::__normal_iterator<typename _Alloc::pointer, std::basic_string<_CharT, _Traits, _Alloc> >, _InputIterator, _InputIterator) [with _InputIterator = int, _CharT = char, _Traits = std::char_traits<char>, _Alloc = std::allocator<char>]'\n/usr/include/c++/3.3/bits/basic_string.h:492:   instantiated from `std::basic_string<_CharT, _Traits, _Alloc>& std::basic_string<_CharT, _Traits, _Alloc>::append(_InputIterator, _InputIterator) [with _InputIterator = int, _CharT = char, _Traits = std::char_traits<char>, _Alloc = std::allocator<char>]'\nsrc/errorlogger.cpp:70:   instantiated from here\n/usr/include/c++/3.3/bits/stl_iterator_base_types.h:126: error: `int' is not a \n   class, struct, or union type\n/usr/include/c++/3.3/bits/stl_iterator_base_types.h:127: error: `int' is not a \n   class, struct, or union type\n/usr/include/c++/3.3/bits/stl_iterator_base_types.h:128: error: `int' is not a \n   class, struct, or union type\n/usr/include/c++/3.3/bits/stl_iterator_base_types.h:129: error: `int' is not a \n   class, struct, or union type\n/usr/include/c++/3.3/bits/stl_iterator_base_types.h:130: error: `int' is not a \n   class, struct, or union type\n/usr/include/c++/3.3/bits/basic_string.h: In member function `\n   std::basic_string<_CharT, _Traits, _Alloc>& std::basic_string<_CharT, \n   _Traits, _Alloc>::replace(__gnu_cxx::__normal_iterator<typename \n   _Alloc::pointer, std::basic_string<_CharT, _Traits, _Alloc> >, \n   __gnu_cxx::__normal_iterator<typename _Alloc::pointer, \n   std::basic_string<_CharT, _Traits, _Alloc> >, _InputIterator, \n   _InputIterator) [with _InputIterator = int, _CharT = char, _Traits = \n   std::char_traits<char>, _Alloc = std::allocator<char>]':\n/usr/include/c++/3.3/bits/basic_string.h:492:   instantiated from `std::basic_string<_CharT, _Traits, _Alloc>& std::basic_string<_CharT, _Traits, _Alloc>::append(_InputIterator, _InputIterator) [with _InputIterator = int, _CharT = char, _Traits = std::char_traits<char>, _Alloc = std::allocator<char>]'\nsrc/errorlogger.cpp:70:   instantiated from here\n/usr/include/c++/3.3/bits/basic_string.h:624: error: no type named `\n   iterator_category' in `struct std::iterator_traits<int>'\nmake: *** [src/errorlogger.o] Error 1\n\n\n", 
    "reporter": "ettlmartin", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1236538402000000", 
    "component": "Other", 
    "summary": "unable to compile with g++-3.3", 
    "priority": "", 
    "keywords": "", 
    "time": "2009-03-08T18:12:39", 
    "milestone": "1.30", 
    "owner": "aggro80", 
    "type": "defect"
}
```
